### ISSUE TITLE
functest-run-suite test failure results in exception, model not torn down

### ISSUE THREAD

**Issue by stub42** [openstack-charmers/zaza#284]
functest-run-suite terminates with an AssertionError exception and traceback when my test fails, and the model is not torn down. --keep-model is not being used.

```
2019-09-03 17:44:28 [INFO] Ran 1 test in 3.517s
2019-09-03 17:44:28 [INFO] FAILED
2019-09-03 17:44:28 [INFO]  (errors=1)
Traceback (most recent call last):
  File "/home/stub/charms/postgresql/.tox/func/bin/functest-run-suite", line 10, in <module>
    sys.exit(main())
  File "/home/stub/charms/postgresql/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 140, in main
    bundle=args.bundle)
  File "/home/stub/charms/postgresql/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 76, in func_test_runner
    test_steps.get(model_alias, []))
  File "/home/stub/charms/postgresql/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/test.py", line 68, in test
    run_test_list(tests)
  File "/home/stub/charms/postgresql/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/test.py", line 62, in run_test_list
    assert test_result.wasSuccessful(), "Test run failed"
AssertionError: Test run failed
ERROR: InvocationError: '/home/stub/charms/postgresql/.tox/func/bin/functest-run-suite --smoke'
_______________________________________________________________________________ summary ________________________________________________________________________________
ERROR:   func: commands failed
```

**Comment by auria** [comment]
I think this issue can be closed now. 2 new 'keep model' flags have been added. Besides, when no flags are used, all models are destroyed (except if KeyboardInterrupt or a signal is caught - libs used underneath will fail causing the model.destroy logic to not be run).

**Comment by ajkavanagh** [comment]
I tend to agree with @auria that this is probably overtaken by events.  Thanks for updating @auria !
