### ISSUE TITLE
model alias may be broken

### ISSUE THREAD

**Issue by ryan-beisner** [openstack-charmers/zaza#302]
Example:  clone the percona-cluster charm, try to run zaza func tests with `tox -e func` and witness:

```
(func-noop) 1 ubuntu@beisner-bastion:~/git/charm-percona-cluster$ functest-run-suite --keep-model --smoke
Traceback (most recent call last):
  File "/home/ubuntu/git/charm-percona-cluster/.tox/func-noop/bin/functest-run-suite", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/git/charm-percona-cluster/.tox/func-noop/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 162, in main
    bundle=args.bundle)
  File "/home/ubuntu/git/charm-percona-cluster/.tox/func-noop/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 100, in func_test_runner
    environment_deploys = utils.get_environment_deploys(bundle_key)
  File "/home/ubuntu/git/charm-percona-cluster/.tox/func-noop/lib/python3.6/site-packages/zaza/charm_lifecycle/utils.py", line 211, in get_environment_deploys
    environment_deploys.append(get_environment_deploy(bundle_mapping))
  File "/home/ubuntu/git/charm-percona-cluster/.tox/func-noop/lib/python3.6/site-packages/zaza/charm_lifecycle/utils.py", line 124, in get_environment_deploy
    return env_deploy_f[get_deployment_type(deployment_directive)](
KeyError: None
```

**Comment by ryan-beisner** [comment]
Observed here:
https://review.opendev.org/#/c/685850/

Confirmed on percona-cluster charm @ master:
```
ubuntu@beisner-bastion:~/git/charm-percona-cluster$ tox -e func
func create: /home/ubuntu/git/charm-percona-cluster/.tox/func
func installdeps: -r/home/ubuntu/git/charm-percona-cluster/test-requirements.txt
func installed: aodhclient==1.3.0,appdirs==1.4.3,asn1crypto==1.0.1,async-generator==1.10,Babel==2.7.0,bcrypt==3.1.7,blessings==1.6,certifi==2019.9.11,cffi==1.12.3,chardet==3.0.4,charm-tools==2.7.2,charmhelpers==0.20.4,Cheetah3==3.2.4,cliff==2.16.0,cmd2==0.8.9,colander==1.7.0,coverage==4.5.4,cryptography==2.7,debtcollector==1.22.0,decorator==4.4.0,dict2colander==0.2,distro==1.4.0,distro-info==0.0.0,dogpile.cache==0.8.0,entrypoints==0.3,extras==1.0.0,fasteners==0.15,fixtures==3.0.0,flake8==2.4.1,future==0.18.0,httplib2==0.14.0,hvac==0.6.4,idna==2.8,importlib-metadata==0.23,iso8601==0.1.12,Jinja2==2.10.3,jmespath==0.9.4,jsonpatch==1.24,jsonpointer==2.0,jsonschema==2.5.1,juju==2.6.3,juju-wait==2.7.0,jujubundlelib==0.5.6,keyring==19.2.0,keystoneauth1==3.17.1,launchpadlib==1.10.7,lazr.restfulclient==0.14.2,lazr.uri==1.0.3,libcharmstore==0.0.9,linecache2==1.0.0,macaroonbakery==1.2.3,MarkupSafe==1.1.1,mccabe==0.3.1,mock==3.0.5,monotonic==1.5,more-itertools==7.2.0,msgpack==0.6.2,munch==2.3.2,netaddr==0.7.19,netifaces==0.10.9,oauthlib==3.1.0,openstacksdk==0.36.0,os-client-config==1.33.0,os-service-types==1.7.0,osc-lib==1.14.1,oslo.concurrency==3.30.0,oslo.config==6.11.1,oslo.context==2.23.0,oslo.i18n==3.24.0,oslo.log==3.44.1,oslo.serialization==2.29.2,oslo.utils==3.41.2,osprofiler==2.8.2,otherstuf==1.1.0,paramiko==2.6.0,parse==1.12.1,path.py==12.0.1,pathspec==0.3.4,pbr==5.4.3,pep8==1.7.1,pika==0.13.1,pkg-resources==0.0.0,prettytable==0.7.2,protobuf==3.10.0,pyasn1==0.4.7,pycparser==2.19,pyflakes==0.8.1,pyinotify==0.9.6,pymacaroons==0.13.0,PyNaCl==1.3.0,pyOpenSSL==19.0.0,pyparsing==2.4.2,pyperclip==1.7.0,pyRFC3339==1.1,python-ceilometerclient==2.9.0,python-cinderclient==5.0.0,python-dateutil==2.8.0,python-glanceclient==2.17.0,python-heatclient==1.18.0,python-keystoneclient==3.21.0,python-mimeparse==1.6.0,python-neutronclient==6.14.0,python-novaclient==15.1.0,python-octaviaclient==1.10.0,python-openstackclient==4.0.0,python-subunit==1.3.0,python-swiftclient==3.8.1,pytz==2019.3,pyudev==0.21.0,PyYAML==3.13,requests==2.22.0,requestsexceptions==1.4.0,rfc3986==1.3.2,ruamel.yaml==0.15.100,SecretStorage==2.3.1,simplejson==3.16.0,six==1.12.0,stestr==2.5.1,stevedore==1.31.0,stuf==0.9.16,Tempita==0.5.2,tenacity==5.1.1,testresources==2.0.1,testtools==2.3.0,theblues==0.5.1,toposort==1.5,traceback2==1.4.0,translationstring==1.3,unittest2==1.1.0,urllib3==1.25.6,vergit==1.0.2,virtualenv==16.7.5,voluptuous==0.11.7,wadllib==1.3.3,warlock==1.3.3,wcwidth==0.1.7,WebOb==1.8.5,websockets==7.0,wrapt==1.11.2,zaza==0.0.2.dev1,zaza.openstack==0.0.1.dev1,zipp==0.6.0
func runtests: PYTHONHASHSEED='0'
func runtests: commands[0] | functest-run-suite --keep-model
Traceback (most recent call last):
  File "/home/ubuntu/git/charm-percona-cluster/.tox/func/bin/functest-run-suite", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/git/charm-percona-cluster/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 162, in main
    bundle=args.bundle)
  File "/home/ubuntu/git/charm-percona-cluster/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 100, in func_test_runner
    environment_deploys = utils.get_environment_deploys(bundle_key)
  File "/home/ubuntu/git/charm-percona-cluster/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/utils.py", line 211, in get_environment_deploys
    environment_deploys.append(get_environment_deploy(bundle_mapping))
  File "/home/ubuntu/git/charm-percona-cluster/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/utils.py", line 124, in get_environment_deploy
    return env_deploy_f[get_deployment_type(deployment_directive)](
KeyError: None
```

Checked zaza and zaza-openstack-tests unit tests at master, both pass.

**Comment by ryan-beisner** [comment]
FYI, pip freeze from the percona-cluster tox run:

```
Babel==2.7.0
Cheetah3==3.2.4
Jinja2==2.10.3
MarkupSafe==1.1.1
PyNaCl==1.3.0
PyYAML==3.13
SecretStorage==2.3.1
Tempita==0.5.2
WebOb==1.8.5
aodhclient==1.3.0
appdirs==1.4.3
asn1crypto==1.0.1
async-generator==1.10
bcrypt==3.1.7
blessings==1.6
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
charm-tools==2.7.2
charmhelpers==0.20.4
cliff==2.16.0
cmd2==0.8.9
colander==1.7.0
coverage==4.5.4
cryptography==2.7
debtcollector==1.22.0
decorator==4.4.0
dict2colander==0.2
distro-info==0.0.0
distro==1.4.0
dogpile.cache==0.8.0
entrypoints==0.3
extras==1.0.0
fasteners==0.15
fixtures==3.0.0
flake8==2.4.1
future==0.18.0
httplib2==0.14.0
hvac==0.6.4
idna==2.8
importlib-metadata==0.23
iso8601==0.1.12
jmespath==0.9.4
jsonpatch==1.24
jsonpointer==2.0
jsonschema==2.5.1
juju-wait==2.7.0
juju==2.6.3
jujubundlelib==0.5.6
keyring==19.2.0
keystoneauth1==3.17.1
launchpadlib==1.10.7
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
libcharmstore==0.0.9
linecache2==1.0.0
macaroonbakery==1.2.3
mccabe==0.3.1
mock==3.0.5
monotonic==1.5
more-itertools==7.2.0
msgpack==0.6.2
munch==2.3.2
netaddr==0.7.19
netifaces==0.10.9
oauthlib==3.1.0
openstacksdk==0.36.0
os-client-config==1.33.0
os-service-types==1.7.0
osc-lib==1.14.1
oslo.concurrency==3.30.0
oslo.config==6.11.1
oslo.context==2.23.0
oslo.i18n==3.24.0
oslo.log==3.44.1
oslo.serialization==2.29.2
oslo.utils==3.41.2
osprofiler==2.8.2
otherstuf==1.1.0
paramiko==2.6.0
parse==1.12.1
path.py==12.0.1
pathspec==0.3.4
pbr==5.4.3
pep8==1.7.1
pika==0.13.1
pkg-resources==0.0.0
prettytable==0.7.2
protobuf==3.10.0
pyOpenSSL==19.0.0
pyRFC3339==1.1
pyasn1==0.4.7
pycparser==2.19
pyflakes==0.8.1
pyinotify==0.9.6
pymacaroons==0.13.0
pyparsing==2.4.2
pyperclip==1.7.0
python-ceilometerclient==2.9.0
python-cinderclient==5.0.0
python-dateutil==2.8.0
python-glanceclient==2.17.0
python-heatclient==1.18.0
python-keystoneclient==3.21.0
python-mimeparse==1.6.0
python-neutronclient==6.14.0
python-novaclient==15.1.0
python-octaviaclient==1.10.0
python-openstackclient==4.0.0
python-subunit==1.3.0
python-swiftclient==3.8.1
pytz==2019.3
pyudev==0.21.0
requests==2.22.0
requestsexceptions==1.4.0
rfc3986==1.3.2
ruamel.yaml==0.15.100
simplejson==3.16.0
six==1.12.0
stestr==2.5.1
stevedore==1.31.0
stuf==0.9.16
tenacity==5.1.1
testresources==2.0.1
testtools==2.3.0
theblues==0.5.1
toposort==1.5
traceback2==1.4.0
translationstring==1.3
unittest2==1.1.0
urllib3==1.25.6
vergit==1.0.2
virtualenv==16.7.5
voluptuous==0.11.7
wadllib==1.3.3
warlock==1.3.3
wcwidth==0.1.7
websockets==7.0
wrapt==1.11.2
zaza.openstack==0.0.1.dev1
zaza==0.0.2.dev1
zipp==0.6.0
```

**Comment by ryan-beisner** [comment]
Also visible on:
glance-simplestreams-sync https://review.opendev.org/#/c/685827/

**Comment by ryan-beisner** [comment]
Issue looks to be resolved by https://github.com/openstack-charmers/zaza/pull/303 - tyvm!
