### ISSUE TITLE
Setting raise_on_failure=True for zaza.model.run_action() raises KeyError

### ISSUE THREAD

**Issue by zzehring** [openstack-charmers/zaza#314]
Receiving a `KeyError: 'parameters'` when raise_on_failure=True for zaza.model.run_action(), where the action itself fails.

```
2019-12-10 17:06:01 [INFO] Traceback (most recent call last):
2019-12-10 17:06:01 [INFO]   File "./tests/functional/utils.py", line 27, in wrapped_f
2019-12-10 17:06:01 [INFO]     f(*args)
2019-12-10 17:06:01 [INFO]   File "./tests/functional/test_duplicity.py", line 193, in test_sftp_full_do_backup
2019-12-10 17:06:01 [INFO]     zaza.model.run_action(self.duplicity_unit.name, self.action, raise_on_failure=True)
2019-12-10 17:06:01 [INFO]   File "/home/user/Projects/Charms/charm-duplicity/.tox/func-noop/lib/python3.7/site-packages/zaza/__init__.py", line 48, in _wrapper
2019-12-10 17:06:01 [INFO]     return run(_run_it())
2019-12-10 17:06:01 [INFO]   File "/home/user/Projects/Charms/charm-duplicity/.tox/func-noop/lib/python3.7/site-packages/zaza/__init__.py", line 36, in run
2019-12-10 17:06:01 [INFO]     return task.result()
2019-12-10 17:06:01 [INFO]   File "/home/user/Projects/Charms/charm-duplicity/.tox/func-noop/lib/python3.7/site-packages/zaza/__init__.py", line 47, in _run_it
2019-12-10 17:06:01 [INFO]     return await f(*args, **kwargs)
2019-12-10 17:06:01 [INFO]   File "/home/zackz/Projects/Charms/charm-duplicity/.tox/func-noop/lib/python3.7/site-packages/zaza/model.py", line 589, in async_run_action
2019-12-10 17:06:01 [INFO]     raise ActionFailed(action_obj)
2019-12-10 17:06:01 [INFO]   File "/home/zackz/Projects/Charms/charm-duplicity/.tox/func-noop/lib/python3.7/site-packages/zaza/model.py", line 557, in __init__
2019-12-10 17:06:01 [INFO]     .format(action.name, action.parameters, action.receiver,
2019-12-10 17:06:01 [INFO]   File "/home/zackz/Projects/Charms/charm-duplicity/.tox/func-noop/lib/python3.7/site-packages/juju/model.py", line 266, in __getattr__
2019-12-10 17:06:01 [INFO]     return self.safe_data[name]
2019-12-10 17:06:01 [INFO] KeyError: 'parameters'
2019-12-10 17:06:01 [INFO] ----------------------------------------------------------------------
```

It looks like the code as an issue when retrieving action.parameters where parameters does not exist in action dict:
```
message = ('Run of action "{}" with parameters "{}" on "{}" failed '
                   'with "{}" (id={} status={} enqueued={} started={} '
                   'completed={})'
                   .format(action.name, action.parameters, action.receiver,
                           action.message, action.id, action.status,
                           action.enqueued, action.started, action.completed))
```

**Comment by Vultaire** [comment]
I hit the same issue today with a freshly installed zaza.

**Comment by ajkavanagh** [comment]
Should be closed by #355 ... please re-open if it causes a problem again.  Thanks.

**Comment by AurelienLourot** [comment]
This seems to be still happening, e.g. [here](https://openstack-ci-reports.ubuntu.com/artifacts/test_charm_pipeline_func_smoke/openstack/charm-glance-simplestreams-sync/743022/1/18314/consoleText.test_charm_func_smoke_18635.txt)

```
Traceback (most recent call last):
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/bin/functest-run-suite", line 8, in <module>
    sys.exit(main())
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 204, in main
    force=args.force)
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 141, in func_test_runner
    force=force)
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 83, in run_env_deployment
    config_steps.get(deployment.model_alias, []))
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/charm_lifecycle/configure.py", line 48, in configure
    run_configure_list(functions)
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/charm_lifecycle/configure.py", line 37, in run_configure_list
    utils.get_class(func)()
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/openstack/charm_tests/glance_simplestreams_sync/setup.py", line 38, in sync_images
    action_params={},
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/__init__.py", line 48, in _wrapper
    return run(_run_it())
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/__init__.py", line 36, in run
    return task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/__init__.py", line 47, in _run_it
    return await f(*args, **kwargs)
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/model.py", line 668, in async_run_action_on_leader
    raise ActionFailed(action_obj)
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/model.py", line 597, in __init__
    'enqueued', 'started', 'completed']}
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/zaza/model.py", line 595, in <dictcomp>
    for key in ['name', 'parameters', 'receiver',
  File "/tmp/tmp.jV6QFyY9NO/func-smoke/lib/python3.5/site-packages/juju/model.py", line 273, in __getattr__
    return self.safe_data[name]
KeyError: 'parameters'
```

**Comment by ajkavanagh** [comment]
Ah, it's actually broken in libjuju; we'll have to wrap it differently in zaza.
