### ISSUE TITLE
New Destroy code requires juju clouds.yaml to exist

### ISSUE THREAD

**Issue by afreiberger** [openstack-charmers/zaza#413]
In a lxd/localhost juju environment, ~/.local/share/juju/clouds.yaml does not exist unless you've added a MAAS or Openstack cloud.

2021-01-29 15:33:53 [INFO] Using config /home/drew/.local/share/juju/clouds.yaml
Traceback (most recent call last):
  File "/home/drew/charm-grafana/src/.tox/func/bin/functest-run-suite", line 8, in <module>
    sys.exit(main())
  File "/home/drew/charm-grafana/src/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 278, in main
    test_directory=args.test_directory)
  File "/home/drew/charm-grafana/src/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 213, in func_test_runner
    force=force, test_directory=test_directory)
  File "/home/drew/charm-grafana/src/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 165, in run_env_deployment
    destroy.destroy(model_name)
  File "/home/drew/charm-grafana/src/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/destroy.py", line 39, in destroy
    if juju_utils.get_provider_type() == "openstack":
  File "/home/drew/charm-grafana/src/.tox/func/lib/python3.6/site-packages/zaza/utilities/juju.py", line 312, in get_provider_type
    return get_cloud_configs(cloud)["type"]
  File "/home/drew/charm-grafana/src/.tox/func/lib/python3.6/site-packages/zaza/utilities/juju.py", line 67, in get_cloud_configs
    return generic_utils.get_yaml_config(cloud_config)["clouds"].get(cloud)
  File "/home/drew/charm-grafana/src/.tox/func/lib/python3.6/site-packages/zaza/utilities/generic.py", line 170, in get_yaml_config
    return yaml.safe_load(open(config_file, 'r').read())
FileNotFoundError: [Errno 2] No such file or directory: '/home/drew/.local/share/juju/clouds.yaml'

Please wrap a try around the new code in utils.py where it calls: juju_utils.get_provider_type() to pass on FileNotFound exception to continue to support using zaza against localhost/lxd deployments.

**Comment by afreiberger** [comment]
obvious workaround is touch ~/.local/share/juju/clouds.yaml.

**Comment by ajkavanagh** [comment]
This should be resolved by #414 (I used the wrong 'closes' syntax in the commit message).  Please could you re-validate and close if resolved?  Thanks.

**Comment by afreiberger** [comment]
Works a treat.  Thanks, @ajkavanagh!
