### ISSUE TITLE
[Tracking][security]  cryptography is pinned < 3.4 due to rust; needs resolving over time

### ISSUE THREAD

**Issue by ajkavanagh** [openstack-charmers/zaza#421]
Recent (>=3.4) versions of python cryptography now ship with rust code for some of the operations.  This breaks in some scenarios (e.g. https://github.com/openstack-charmers/zaza-openstack-tests/pull/369).

However, we do not want to remain pinned for long as it is a security related module. The main issue is rust builds for charms.reactive charms which needs a build for each platform.  Or we need to NOT have the rust code.

Related: #420 pins to <3.4 in zaza.

**Comment by AurelienLourot** [comment]
Temporary pinning here as well: 
* https://github.com/openstack-charmers/zaza-openstack-tests/pull/502
* https://review.opendev.org/c/openstack/charm-octavia/+/774704

**Comment by samuelallan72** [comment]
I discovered that pinning to <3.4 breaks on s390x and ppc64el architectures, at least on ubuntu noble. It appears that ubuntu noble ships openssl 3, but [cryptography < 35 does not support openssl 3](https://github.com/pyca/cryptography/issues/9709#issuecomment-1755228280). It crashes at runtime with:

```
ubuntu@P9k-LPAR03:~/charm-nrpe$ tox -e func
func: commands[0] /home/ubuntu/charm-nrpe/tests/functional> functest-run-suite --keep-model
Traceback (most recent call last):
  File "/home/ubuntu/charm-nrpe/.tox/func/bin/functest-run-suite", line 5, in <module>
    from zaza.charm_lifecycle.func_test_runner import main
  File "/home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 24, in <module>
    import zaza.charm_lifecycle.before_deploy as before_deploy
  File "/home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/zaza/charm_lifecycle/before_deploy.py", line 20, in <module>
    import zaza.model
  File "/home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/zaza/model.py", line 39, in <module>
    from juju.model import Model
  File "/home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/juju/model.py", line 25, in <module>
    from . import provisioner, tag, utils, jasyncio
  File "/home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/juju/provisioner.py", line 11, in <module>
    import paramiko
  File "/home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import (
  File "/home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/paramiko/transport.py", line 33, in <module>
    from cryptography.hazmat.primitives.ciphers import (
  File "/home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/aead.py", line 10, in <module>
    from cryptography.hazmat.backends.openssl import aead
  File "/home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 117, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /home/ubuntu/charm-nrpe/.tox/func/lib/python3.10/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: FIPS_mode
func: exit 1 (0.46 seconds) /home/ubuntu/charm-nrpe/tests/functional> functest-run-suite --keep-model pid=150908
  func: FAIL code 1 (0.55=setup[0.09]+cmd[0.46] seconds)
  evaluation failed :( (0.68 seconds)
```

I guess it succeeds on amd64 and arm64 because cryptography provides binary wheels for these architectures. While on s390x and ppc64el, it must build from the source wheel, using libssl-dev v3.
