### ISSUE TITLE
functest-run-suite failed due aodhclient

### ISSUE THREAD

**Issue by rgildein** [openstack-charmers/zaza#464]
Running `functest-run-suite` with following error:

```bash
2021-10-25 14:44:47 [ERROR] Model openstack (zaza-2a697f135664)
Traceback (most recent call last):
  File "/home/rg/code/canonical/juju-verify/.tox/func/bin/functest-run-suite", line 8, in <module>
    sys.exit(main())
  File "/home/rg/code/canonical/juju-verify/.tox/func/lib/python3.9/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 364, in main
    func_test_runner(
  File "/home/rg/code/canonical/juju-verify/.tox/func/lib/python3.9/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 277, in func_test_runner
    run_env_deployment(env_deployment, keep_model=preserve_model,
  File "/home/rg/code/canonical/juju-verify/.tox/func/lib/python3.9/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 151, in run_env_deployment
    configure.configure(
  File "/home/rg/code/canonical/juju-verify/.tox/func/lib/python3.9/site-packages/zaza/charm_lifecycle/configure.py", line 51, in configure
    run_configure_list(functions)
  File "/home/rg/code/canonical/juju-verify/.tox/func/lib/python3.9/site-packages/zaza/charm_lifecycle/configure.py", line 37, in run_configure_list
    utils.get_class(func)()
  File "/home/rg/code/canonical/juju-verify/.tox/func/lib/python3.9/site-packages/zaza/charm_lifecycle/utils.py", line 478, in get_class
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rg/code/canonical/juju-verify/.tox/func/lib/python3.9/site-packages/zaza/openstack/charm_tests/glance/setup.py", line 22, in <module>
    import zaza.openstack.utilities.openstack as openstack_utils
  File "/home/rg/code/canonical/juju-verify/.tox/func/lib/python3.9/site-packages/zaza/openstack/utilities/openstack.py", line 50, in <module>
    from aodhclient.v2 import client as aodh_client
  File "/home/rg/code/canonical/juju-verify/.tox/func/lib/python3.9/site-packages/aodhclient/v2/client.py", line 17, in <module>
    from aodhclient.v2 import alarm
  File "/home/rg/code/canonical/juju-verify/.tox/func/lib/python3.9/site-packages/aodhclient/v2/alarm.py", line 16, in <module>
    from aodhclient import utils
  File "/home/rg/code/canonical/juju-verify/.tox/func/lib/python3.9/site-packages/aodhclient/utils.py", line 43, in <module>
    expr = pp.operatorPrecedence(condition, [
AttributeError: module 'pyparsing' has no attribute 'operatorPrecedence'
ERROR: InvocationError for command /home/rg/code/canonical/juju-verify/.tox/func/bin/functest-run-suite --test-directory tests/functional --keep-all-models (exited with code 1)
_______________________________________________________________________________________________________________ summary ________________________________________________________________________________________________________________
ERROR:   func: commands failed
```

**Comment by r-f-g** [comment]
HI @AurelienLourot  the [review#815258](https://review.opendev.org/c/openstack/charm-rabbitmq-server/+/815258), so maybe this bug cloud be closed?

**Comment by ajkavanagh** [comment]
As @rgildein points out, the associated review has landed; this can be closed.  Thanks for the pointer @rgildein and to @AurelienLourot for the fix!
