### ISSUE TITLE
Using function fail() from unitest gives an unexpected result with no logging of the fail message.

### ISSUE THREAD

**Issue by r-f-g** [openstack-charmers/zaza#467]
Using the fial [1] function in function tests does not work as expected.
If you use `self.fail("<message>")` than you will see following output, which IMO does not make any sense.

```bash
Traceback (most recent call last):
  File "/home/ubuntu/juju-verify/.tox/func-target/bin/functest-test", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/juju-verify/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 197, in main
    test(
  File "/home/ubuntu/juju-verify/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 136, in test
    run_test_list(tests)
  File "/home/ubuntu/juju-verify/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 124, in run_test_list
    get_test_runners()[runner](testcase, _testcase)
  File "/home/ubuntu/juju-verify/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 81, in run_unittest
    assert test_result.wasSuccessful(), "Test run failed"
AssertionError: Test run failed
```

---
[1]: https://docs.python.org/3/library/unittest.html#unittest.TestCase.fail

**Comment by ajkavanagh** [comment]
Hi

Can you flesh this out a bit more, please?  Is there not more logging from the test that did a `fail()`?  I know why it's doing the above, but it would be good to see this output with a bit more context.  Thanks.

**Comment by r-f-g** [comment]
HI @ajkavanagh, there is not much I can add here, because there no more logs. [Here](https://github.com/canonical/juju-verify/runs/4334362973?check_suite_focus=true) is an example of tests that failed (`tests/test_neutron_gateway.py::test_lbaas_warning` triggered `self.fail` function).

**Comment by ajkavanagh** [comment]
So just leaving a few notes.

In unittest, `self.fail(...)` is:

```python
    def fail(self, msg=None):
        """Fail immediately, with the given message."""
        raise self.failureException(msg)
```

and `failureException` is:

```python
    failureException = AssertionError
```

So, essentially, an `AssertionError` is raised when `fail(...)` is called in a test.

The piece of code in zaza that says "Test run failed" is:

```python
def run_unittest(testcase, test_name):
    """Test runner for unittest test cases.

    :param testcase: Class to pass to unittest test runner
    :type testcase: Class
    :param test_name: Name of test for logging.
    :type test_name: str
    """
    # note if the assert fails, the events will be:
    #   (NotifyEvents.TEST_CASE, NotifyType.BEFORE)
    #   (NotifyEvents.TEST_CASE, NotifyEvents.EXCEPTION)
    with notify_around(NotifyEvents.TEST_CASE, testcase=testcase,
                       test_name=test_name):
        suite = unittest.TestLoader().loadTestsFromTestCase(testcase)
        test_result = unittest.TextTestRunner(
            stream=Stream2Logger(),
            verbosity=2).run(suite)
        run_report.register_event_finish('Test {}'.format(test_name))
        assert test_result.wasSuccessful(), "Test run failed"
```

where `wasSuccessful()` is from unittest case.py:

```python
    def wasSuccessful(self):
        "Tells whether or not this result was a success"
        return len(self.failures) == len(self.errors) == 0
```

So, it's basically doing the right thing; it's abandoning the test run due to a test failure.  Note that this is a test class that is bring run, rather than an individual test.

Now as to what to do with this?  Options:

1. It depends on whether `self.fail()` should end the test run or not.  I suspect it should.  This isn't skipping a test, this is saying that it failed.  In zaza, this means 'end of testing', at the moment.
2. It would be useful to log the message from the failure.  We could override the `fail` method and log it, or change the exception and catch that.
3. If we want to do something *else* with `self.fail()` then we should change the exception.

This is probably a feature request now.  I'm also going to change the title of the bug to reflect that what it does might be unexpected, but is exactly what it should be doing.

If you have any thoughts on what it *should* do, then please add them here.

**Comment by r-f-g** [comment]
> Now as to what to do with this? Options:
> 
>     1. It depends on whether `self.fail()` should end the test run or not.  I suspect it should.  This isn't skipping a test, this is saying that it failed.  In zaza, this means 'end of testing', at the moment.

I agree this should do the same as using `assert False` in tests.
> 
>     2. It would be useful to log the message from the failure.  We could override the `fail` method and log it, or change the exception and catch that.

The exception does not need to be changed and we should stick to the classic functionality of unittests. Also, changing the behavior of the `fail` function will be more confusing. 
I believe the best approach is to add `self.failures` and `self.errors` to the `assert test_result.wasSuccessful(), "Test run failed"` line to provide reasons why test failed. The "Test run failed" message doesn't give me much information about the test itself and I have to look in the zaza code/documentation to find out what it is.

**Comment by r-f-g** [comment]
Hi @ajkavanagh, I will close this issue because the real issue was on our side caused by a logging configuration.

Here's an example of how it works.
```bash
$ functest-test -t tests.test_ceph.BaseTests -m zaza-ace1789049d4 --log INFO
2021-11-29 19:27:58 [INFO] ## Running Test tests.test_ceph.BaseTests ##
2021-11-29 19:27:59 [INFO] test_fail (tests.test_ceph.BaseTests)
2021-11-29 19:27:59 [INFO]  ... 
2021-11-29 19:27:59 [INFO] FAIL
2021-11-29 19:27:59 [INFO] ======================================================================
2021-11-29 19:27:59 [INFO] FAIL: test_fail (tests.test_ceph.BaseTests)
2021-11-29 19:27:59 [INFO] ----------------------------------------------------------------------
2021-11-29 19:27:59 [INFO] Traceback (most recent call last):
2021-11-29 19:27:59 [INFO]   File "/home/ubuntu/juju-verify/tests/functional/./tests/test_ceph.py", line 22, in test_fail
2021-11-29 19:27:59 [INFO]     self.fail("This test should failed.")
2021-11-29 19:27:59 [INFO] AssertionError: This test should failed.
2021-11-29 19:27:59 [INFO] ----------------------------------------------------------------------
2021-11-29 19:27:59 [INFO] Ran 1 test in 0.386s
2021-11-29 19:27:59 [INFO] FAILED
2021-11-29 19:27:59 [INFO]  (failures=1)
2021-11-29 19:27:59 [ERROR] test_result: <unittest.runner.TextTestResult run=1 errors=0 failures=1>, {'failfast': False, 'failures': [(<tests.test_ceph.BaseTests testMethod=test_fail>, 'Traceback (most recent call last):\n  File "/home/ubuntu/juju-verify/tests/functional/./tests/test_ceph.py", line 22, in test_fail\n    self.fail("This test should failed.")\nAssertionError: This test should failed.\n')], 'errors': [], 'testsRun': 1, 'skipped': [], 'expectedFailures': [], 'unexpectedSuccesses': [], 'shouldStop': False, 'buffer': False, 'tb_locals': False, '_stdout_buffer': None, '_stderr_buffer': None, '_original_stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>, '_original_stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, '_mirrorOutput': False, 'stream': <unittest.runner._WritelnDecorator object at 0x7fb9acd08160>, 'showAll': True, 'dots': False, 'descriptions': True, '_testRunEntered': False, '_moduleSetUpFailed': False, '_previousTestClass': <class 'tests.test_ceph.BaseTests'>}
Traceback (most recent call last):
  File "/home/ubuntu/juju-verify/.tox/func-target/bin/functest-test", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/juju-verify/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 197, in main
    test(
  File "/home/ubuntu/juju-verify/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 136, in test
    run_test_list(tests)
  File "/home/ubuntu/juju-verify/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 124, in run_test_list
    get_test_runners()[runner](testcase, _testcase)
  File "/home/ubuntu/juju-verify/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 81, in run_unittest
    assert test_result.wasSuccessful(), "Test run failed"
AssertionError: Test run failed
```
