### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by freyes** [openstack-charmers/zaza#470]
Running `tox -e func-target -- focal-ussuri` in the ovn-chassis charm using LXD provider throws this error consistently in my environment.

If I'm reading the stacktrace correctly this is because we are nesting the loops

```
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/vault/utils.py", line 203, in get_clients
    units = zaza.model.get_app_ips('vault')
...
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/model.py", line 700, in async_get_app_ips
    for u in get_units(application_name, model_name=model_name)]
...
```

This is the full stacktrace
```
2022-01-10 20:43:34 [INFO] Running auto_initialize                                                                                                                                                            
2022-01-10 20:43:35 [ERROR] {'default_alias': 'zaza-ce6379620820'}                                                                                                                                            
2022-01-10 20:43:35 [ERROR] Model default_alias (zaza-ce6379620820)                                                                                                                                           
Traceback (most recent call last):                                                                                                                                                                            
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/bin/functest-run-suite", line 8, in <module>                                                                             
    sys.exit(main())                                                                                                                                                                                          
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 374, in main                                 
    func_test_runner(                                                                                                                                                                                         
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 287, in func_test_runner                     
    run_env_deployment(env_deployment, keep_model=preserve_model,                                                                                                                                             
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 155, in run_env_deployment                   
    configure.configure(                                                                                                                                                                                      
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/configure.py", line 58, in configure                                    
    run_configure_list(functions)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/configure.py", line 44, in run_configure_list
    utils.get_class(func)()
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/vault/setup.py", line 162, in auto_initialize
    basic_setup(cacert=cacert, unseal_and_authorize=True)
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/vault/setup.py", line 56, in basic_setup
    vault_svc = vault_utils.VaultFacade(cacert=cacert)
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/vault/utils.py", line 57, in __init__
    self.clients = get_clients(cacert=cacert)
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/vault/utils.py", line 203, in get_clients
    units = zaza.model.get_app_ips('vault')
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py", line 48, in _wrapper
    return run(_run_it())
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py", line 36, in run
    return task.result()
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py", line 47, in _run_it
    return await f(*args, **kwargs)
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/model.py", line 700, in async_get_app_ips
    for u in get_units(application_name, model_name=model_name)]
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py", line 48, in _wrapper
    return run(_run_it())
  File "/home/ubuntu/git/charm-ovn-chassis/build/builds/ovn-chassis/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py", line 35, in run
    loop.run_until_complete(asyncio.wait([task], loop=loop))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
sys:1: RuntimeWarning: coroutine 'wait' was never awaited
```

**Comment by afreiberger** [comment]
As some history, I've seen this when there are nested asyncio threads and the thread isn't passed through the non-async wrappers.  Maybe this is related to the changes today for get_public_addresses that introduced another layer of sync-wrapper inside an async function?

**Comment by afreiberger** [comment]
(we're seeing the same in grafana charm tests that call the same zaza.model.get_app_ips('app_name') function.

**Comment by cjohnston1158** [comment]
confirmed that reverting to commit cb040069b49d152fae37258ee30a11101cd1aebd and the issue as stopped.

**Comment by ajkavanagh** [comment]
I think it's entirely possible that I broke zaza with the last commit.  I'll put up a revert and try again.

**Comment by cjohnston1158** [comment]
I can confirm that using tip is working again.

**Comment by ajkavanagh** [comment]
> I can confirm that using tip is working again.

Based on this, I'm going to close the bug.  Thanks for the confirmation.
