### ISSUE TITLE
Destroy model raises error even though model was destroyed 

### ISSUE THREAD

**Issue by chanchiwai-ray** [openstack-charmers/zaza#559]
Zaza destroy model raises error even though the model was destroyed.  This kind of error message is confusing for people who are debugging the functional tests since it will not crash the functional tests. For reference, the causes of this problem is in https://github.com/openstack-charmers/zaza/blob/master/zaza/controller.py#L50.
```
2022-08-22 02:18:40 [INFO] Finished testing zaza-936a4b98a449
2022-08-22 02:18:40 [INFO] Destroying model zaza-936a4b98a449
2022-08-22 02:18:41 [INFO] Waiting for model to be fully destroyed: attempt: 1
2022-08-22 02:18:51 [INFO] Waiting for model to be fully destroyed: attempt: 2
2022-08-22 02:18:58 [ERROR] Error in watcher
Traceback (most recent call last):
  File "/home/kaido/charm-userdir-ldap/.tox/func/lib/python3.8/site-packages/juju/model.py", line 1125, in _all_watcher
    _post_step(new_obj)
  File "/home/kaido/charm-userdir-ldap/.tox/func/lib/python3.8/site-packages/juju/model.py", line 1053, in _post_step
    if isinstance(obj, ModelInfo) and obj.safe_data is not None:
  File "/home/kaido/charm-userdir-ldap/.tox/func/lib/python3.8/site-packages/juju/model.py", line 371, in safe_data
    raise DeadEntityException(
juju.exceptions.DeadEntityException: Entity model:a32915fd-f2fd-4743-8eef-c2dac3ded0e2 is dead - its attributes can no longer be accessed. Use the .previous() method on this object to get a copy of the object at its previous state.
2022-08-22 02:18:58 [ERROR] Task exception was never retrieved
future: <Task finished name='Task-115' coro=<Model._watch.<locals>._all_watcher() done, defined at /home/kaido/charm-userdir-ldap/.tox/func/lib/python3.8/site-packages/juju/model.py:1058> exception=DeadEntityException('Entity model:a32915fd-f2fd-4743-8eef-c2dac3ded0e2 is dead - its attributes can no longer be accessed. Use the .previous() method on this object to get a copy of the object at its previous state.')>
Traceback (most recent call last):
  File "/home/kaido/charm-userdir-ldap/.tox/func/lib/python3.8/site-packages/juju/model.py", line 1125, in _all_watcher
    _post_step(new_obj)
  File "/home/kaido/charm-userdir-ldap/.tox/func/lib/python3.8/site-packages/juju/model.py", line 1053, in _post_step
    if isinstance(obj, ModelInfo) and obj.safe_data is not None:
  File "/home/kaido/charm-userdir-ldap/.tox/func/lib/python3.8/site-packages/juju/model.py", line 371, in safe_data
    raise DeadEntityException(
juju.exceptions.DeadEntityException: Entity model:a32915fd-f2fd-4743-8eef-c2dac3ded0e2 is dead - its attributes can no longer be accessed. Use the .previous() method on this object to get a copy of the object at its previous state.
2022-08-22 02:19:01 [INFO] Waiting for model to be fully destroyed: attempt: 3
2022-08-22 02:19:01 [INFO] Model zaza-936a4b98a449 destroyed.
```

**Comment by ajkavanagh** [comment]
So, `watcher` is a libjuju entity that is created by libjuju when the model is connected.  Unfortunately, sometimes libjuju doesn't clean-up after itself.  i.e. I don't *think* that this is a zaza error, but rather  a libjuju issue.
